language: c

os:
  - linux

before_install:
  - sudo bash -c "echo deb http://badgerports.org precise main >> /etc/apt/sources.list"
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0E1FAD0C
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel

install:
  - mozroots --import --sync --quiet
  - mono ./.nuget/NuGet.exe restore ./ScriptCs.sln

script:
  - xbuild ./ScriptCs.sln /property:Configuration=Release /nologo /verbosity:normal
  - mono test/xunit/xunit.console.clr4.x86.exe test/ScriptCs.xunit
